name: Testing the library with composer and PHPunit

on: [push, pull_request]

jobs:
    symfony:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
              with:
                php-version: '7.4'
                # extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
                coverage: xdebug #optional

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run PHPunit test suite
              run: vendor/bin/phpunit
